### ISSUE TITLE
backtick breaking insertion

### ISSUE THREAD

**Issue by mellotanica** [vit-project/vit#19]
automated insertions (e.g. command `a`, `A`) are vulnerable to backtick ` character, if one writes a line of text containing two backticks, the program tries to execute what stands between them, like bash would do.

maybe strings should be sanitized in some way before being passed to task when executing these commands?

obviously this behavior is correct when using `:!` or `t` commands

**Comment by scottkosty** [comment]
> automated insertions (e.g. command a, A) are vulnerable to backtick ` character

For 'A' this should not be the case. Are you sure you're using the 1.3 branch?

For 'a', the backticks are indeed interpreted by the shell, because we want to allow Taskwarrior to parse the command (e.g. we want Taskwarrior to interpret "due:3days" for the add command, as opposed to the annotate command). Instead of sanitizing the strings, which I think could be complicated to do perfectly, we could have two prompt modes, one where everything is quoted (which is the current case of annotate), and one where everything is passed to the shell (which is the current case of add), and the user would be able to easily switch between the modes.

**Comment by mellotanica** [comment]
> For 'A' this should not be the case. Are you sure you're using the 1.3 branch?

it actually does not work properly, i'm on 1.3, if i try to annotate a task with something like
```annotation with `backticks` works?```
the task results annotated with
```annotation with  works?```
it does not complain about `batkticks` not being a known executable like 'a' does, but it still tries to execute the command, in fact leaving an annotation like
```annotation with `pwd` works?```
results in 
```annotation with /data/repos/vit works?```


being able to switch between the two versions would be nice, for 'a' in "sanitized" mode one could also prompt for a second line of arguments after the task name, allowing the additional parameters to be passed to task

**Comment by scottkosty** [comment]
hmmm OK then with A something is broken. For me, if I do A and then

    annotation with `pwd` works?

I get that as the literal annotation, no pwd command is run. I'd like to figure out why we see differences. What is the output for you of the following command?

    vit --version



> one could also prompt for a second line of arguments after the task name, allowing the additional parameters to be passed to task

This is an interesting idea. I didn't think about that. So you are suggesting a double prompt. In the first prompt the user would enter the task description, and for this prompt the default would be to have everything escaped. For the second prompt, the user would enter a string that is meant to be parsed by Taskwarrior (e.g. "due:3days wait:1day"). The second prompt would not be quoted when passed. Did I understand that correctly?

**Comment by scottkosty** [comment]
Note that part of the discussion here is related to #15.

**Comment by mellotanica** [comment]
ok, i'm taking everything back, it was all my fault..
i forgot to set the correct prefix while configuring vit and i was still running the old version.
the updated version works flawlessly

>  Did I understand that correctly?
yes! that's exactly what i meant, i know it's not that much vim-like, but it would be pretty useful for strange people like me that speak a language full of accents and use a standard american keyboard (the direct consequence is that there are many backticks in task names and annotations)

**Comment by scottkosty** [comment]
> i forgot to set the correct prefix while configuring vit

No worries at all, I've done that many times. I'm glad we figured out that mystery.

> pretty useful for strange people like me that speak a language full of accents and use a standard american keyboard (the direct consequence is that there are many backticks in task names and annotations)

Can you give an example of what you mean? Having a good understanding of this use case will help me understand the problem better. For example, on a Spanish keyboard, to write `é`, one presses first the `'` key, and then the `e` key. Is that what you mean? I don't see how it relates to this discussion though so that makes me think I'm missing something.

By the way, accents should work much better with VIT 1.3 than they did with 1.2.

**Comment by mellotanica** [comment]
>  Is that what you mean?

my situation is this: i tend to write lots of notes in italian, but i use an american keyboard with american standard layout which is pretty useful for writing code and using the shell, so i don't have dead keys enabled and all the accents i use for notes and speech text are "faked" with the backtick, it's not a good habit but it's pretty comfortable to me.. so to sum up, when i need to write 'è' i actually write 'e`' (sorry for not using the correct markdown but escaping the backticks seems to be a bit too tough here) and if there are two accented letters in a sentence i use as a task topic it results at least in a wrong sentence, some times i lose all the row if there is an exceptionally unfortunate character sequence between two backticks

**Comment by scottkosty** [comment]
Ah I see now better what you mean. Thanks for the explanation and use case.

**Comment by fdela** [comment]
This works with 2.x branch and 1.3 is not receiving non-security updates, so this issue should probably be closed.
