### ISSUE TITLE
vit 2.x: coloring for entire row

### ISSUE THREAD

**Issue by dustymabe** [vit-project/vit#205]
In vit 2.x the coloring was changed to "Per-column colorization with markers". I'm so used to the old (1.x) colorization scheme where the entire row would highlight red or blue or orange depending on the task or the state of the task. Is there any way to get that old behavior back (simple config setting maybe?)?

**Comment by thehunmonkgroup** [comment]
I'm afraid not -- VIT 1.x simply wrapped TaskWarrior's output, which is why it displayed TaskWarrior's colorization.

VIT 2.x builds its output from scratch, thus it would require me to build a bunch of custom logic to handle colorization exactly the same way that TaskWarrior does -- this is kind of hard to justify when I think the new colorization approach is better ;)

You can read a bit more about the new colorization scheme here: https://github.com/scottkosty/vit/blob/2.x/COLOR.md

It's possible in the future, if the colorization logic becomes pluggable, that somebody could write a plugin to emulate the current TaskWarrior colorization logic -- that architecture is a long way off though...
