### ISSUE TITLE
Switching between views much slower in version 2 than in version 1

### ISSUE THREAD

**Issue by thomasrebele** [vit-project/vit#216]
When I go from a view like `:blocking` to another that has many tasks like `:ready`, there's a noticeable lag in version 2. Nice feature btw, to measure the elapsed time. For this scenario it printed `Exec. time: 386ms`. Version 1.3 handles the switch almost instantaneously.

Is there a way to optimize this?

**Comment by thehunmonkgroup** [comment]
Yep, this is a known weakness in 2.x.

FWIW, I did a *lot* of optimizing already. That number used to be a lot higher!

I'm open to clean ways to continue to optimize, but first it's important to understand a little more about the architectural differences between 1.x and 2.x: https://github.com/scottkosty/vit/blob/2.x/DEVELOPMENT.md#architecture

From my testing, the biggest bottleneck is sorting the exported tasks in Python. Taskwarrior provides no way to sort on export, and in order to get a lot of the improvements in 2.x, we need to work with the raw task data and not the final output of Taskwarrior (as 1.x did).

That being said, sorting 1K tasks in C is probably noticeably faster than Python. Perhaps there's some kind of C plugin thing that could be done that the Python code could talk to, and that would be built on package install? The thing is, anything like that is a bit out of my current Python chops, and I don't really have time to figure it out.

As a side note, I do find it amusing that I've become so used to the instant gratification of modern processers, that I too would interpret 386ms as a 'noticeable lag' ;)

**Comment by thomasrebele** [comment]
Sorting my 60 tasks should not take more than 10ms on my i3-7100 laptop with 2.4GHz.

It seems to me that 50% of the time is spent here in my case: https://github.com/scottkosty/vit/blob/a2121f31a4554cf4cf3ddca93bbbcec3309828fc/vit/task_list.py#L239

**Comment by thomasrebele** [comment]
Part of the problem seems to be the `list` in https://github.com/scottkosty/vit/blob/a2121f31a4554cf4cf3ddca93bbbcec3309828fc/vit/formatter/depends.py#L6

I have several tasks with dependencies. Every call to the formatter takes about 10ms. The depends variable is of type `tasklib.lazy.LazyUUIDTaskSet`. If I understand it correctly, every time a tasks is formatted, its dependency tasks will be looked up.

Indeed, a quick benchmark shows the difference (averaged over 10 executions):

`ready`: 117ms (40 tasks to show)
`next`:  217ms (the 40 previous tasks + 8 blocked tasks)

Any ideas how to improve this? Might need some changes in robgolding/tasklib?

**Comment by thehunmonkgroup** [comment]
This is a good catch, I don't use dependencies at all in my workflow, so hadn't ever noticed the performance issue.

VIT might be the wrong layer to address the fundamental issue, perhaps the result of the discussion at https://github.com/robgolding/tasklib/issues/70 can add some kind of functionality to force load ```LazyUUIDTaskSet```? I'm not familiar with the tasklib architecture, but ideally, there would be some kind of caching for ```LazyUUIDTaskSet``` so it only had to be lazily loaded once.

Failing that solution, another fairly sensible path would be to pre-load all the blocking tasks, and use that generated list to do dependency lookups. We're *almost* doing that already: in ```application.py```, there's a ```refresh_blocking_task_uuids()``` helper method that gets called for each report refresh. This is currently used to show the blocking task marker as appropriate, and that data is even passed to the instantiated ```Marker``` class, which is a subclass of the base ```Formatter``` class.

So in theory, the VIT-only fix would be:

1. Change  ```refresh_blocking_task_uuids()``` to load all blocking task data instead of just the uuids
2. Parse the JSON, then turn the list of tasks into a dict of tasks, keyed on uuid
3. Pass that dict into the base ```Formatter``` class
4. Adjust the ```Marker``` class to use the dict keys to do its work
5. Use the dict to look up depends data instead of the tasks ```depends``` key

The main downside of this approach is that it would introduce some more overhead on **all** report loads if the user had any blocking tasks, the more blocking tasks the more overhead, due to:

 * Loading over all the task data per task instead of just the uuid per task
 * Having to parse the JSON result instead of simply splitting the uuids string
 * Building the final, usable dict from the parsed JSON array.

However, I bet this downside is pretty minor since:
 * The data is loading locally
 * Python JSON parsing is probably pretty optimized
 * Converting a list to a dict in Python is probably pretty optimized

Finally, there would basically be no downside at all for VIT users (like myself) that don't make use of task dependencies.

**Comment by thehunmonkgroup** [comment]
Looks like this was handled by https://github.com/robgolding/tasklib/pull/71 so closing for now. Feel free to reopen if it needs further examination.

**Comment by thomasrebele** [comment]
Indeed, performance is much better now. There's still a small lag compared to v1, but in the order of about 100ms. It's now good enough to consider switching to v2. Thank you for your help!
