### ISSUE TITLE
Tab completion of multi-word projects does not include escaping spaces

### ISSUE THREAD

**Issue by ipwnponies** [vit-project/vit#221]
Taskwarrior supports spaces in projects:
```sh
task add foo project:'bar baz'
```

In Vit, this will tab complete but without escaping the space character. This happens everywhere that project completions exist, such as for "modify project":
```
Project: bar baz
```

In this example, Vit will change the project to "bar" and drop "baz" as extra input.
The workaround is to add a backslash escape, same as you would do if you wanted taskwarrior to parse multi-word field as single token (project, duration, string substitution).

More generally, maybe this is a bug for all completions, they currently only work with single words?

**Comment by thehunmonkgroup** [comment]
This shouldn't be very hard to fix, but I'm not sure of the optimal approach. I see three options:

1. ```project:foo\ bar```
2. ```project:'foo bar'```
3. ```project:"foo bar"```

Because of the design of tab completion, we have to end up with the correct escaping syntax -- we can't add it after the command is entered.

Since the meta tags themselves can't be quoted, I'd favor number two -- the visual grouping is better, and single quotes are less noisy.

Thoughts?

P.S. While playing with this issue, I uncovered #222

**Comment by ipwnponies** [comment]
I feel like any of these would work, they're all well understood w.r.t. shell syntax for handling multi-word parameters. If i had to give some opinion, I'd also lean towards #&#x2060;2:
- backslashes are ugly
- double-quotes can result in unintended shell expansion if user copy-pastes `vit` output to execute on the shell or when using it interchangeably as `taskwarrior` input (e.g. for taskwarrior bug report).

**Comment by thehunmonkgroup** [comment]
This is blocked on #222, and I could use some help on that one.

**Comment by thehunmonkgroup** [comment]
https://github.com/scottkosty/vit/commit/41d046e86c1ff73a95d78b66149e3fb30a6aac85 should *mostly* fix this, please try it out and verify.

Closing this for now, a more long-term solution can be dealt with in #230
