### ISSUE TITLE
Add support for simultaneously working with multiple task databases

### ISSUE THREAD

**Issue by sucrecacao** [vit-project/vit#233]
## origin of the problem 
I like to have multiple `.task` folder compartimented. I will create one for each  of my side-project or each one of my courses or what not. I store them locally, at the root of the project's directory. My `home` folder would look like this:
```
home
├── side_projects
│   ├── bar
│       ├── …
│       └── .task
│   └── foo
│       ├── …
│       └── .task
└── uni
    ├── alorithm
    │   ├── …
    │   └── .task
    └── linear_alg
        ├── …
        └── .task

```
This has plenty of advantage that will  discussed later. But one of the downside is that sometime you want to have control on more that once task warrior database.   
That why I would like to fork `vit` to add this new feature of being able to manage multiple `.task` folder at once. 
For example, if I want to manage the tasks for all my university courses, I could run something like ( assuming the same tree as above ):
` find uni/  -name '.task' | vit`
The above would open one vit session displaying all tasks from `uni/algorithm/.task` and `uni/linear_alg/.task`.
same with my side project ( but with other command )
```bash
cd side_project
 find .  -name '.task' | vit
```
or to manage all my computer tasks:
` find $HOME  -name '.task' | vit`

## why not using task warrior "project" attribute
They are equivalent in the sense that we use the folder path instead of the task warrior attribute. We do:
```bash
cd uni/algorithm
task add readXXX
```
instead of:
`task add readXXX project:uni/algorithm`

but the first offer lots of more elegant behavior:
### sharing on multiple computer
Let's say that I work my "foo" side project with a friends that also use tw, now we can share a tw instance in our git repo that only focus on foo's tasks. But on our local machine, we can both append those tasks to our main todo list.
Or let's say that I work on the "bar" project on my personal laptop and at my job's computer. I am very happy to pull strictly only  the project related task on my work computer, without all my personal life tasks.
### Less verbose, more natural behavior
I notice that I usually focus on one activity at the time and manage, and I manage my todo list the same way. I other word, it's lets verbose to do:
``` 
cd uni/algorithm
task add read page ...
task add do exercise ...
task add send mail TA
open algoBook.pdf 
```
than
```
task add read page ... project:uni/algorithm
task add do exercise ... project:uni/algorithm
task add send mail TA project:uni/algorithm
open uni/alorithm/algoBook.pdf
```   
Another elegant behavior is if for some reason the project "foo" has no reason to exist and I delete the folder, then all the related tasks will disappear at the same time. Awesome ! 

## what I have done so far and the help I need
For the moment I just merge all my `pending.data` files into a new temporary file and open it with `vit`. This give me only the ability to read the tasks, but not to modify them as every modification will only affect the temporary file.

After download the source code and browsing around I still had trouble understanding how it worked and where to start.
I would  love if I you could give me some pointers on the function I should look at. And also some hint on how I should implemented the feature. I would be happy to make a pull request if you think the idea is interesting, if not I would appreciate if you can still help me implement it.

**Comment by scottkosty** [comment]
Hi,

Is your goal to load different task databases into one VIT session or separate VIT sessions? Why are the task databases not just merged into one database? I currently don't think there's a high chance of this feature being accepted into core VIT, but if you give details on your specific use case, we can understand more what you're trying to do and why you're trying to do it.

Also, could you please edit the title of this issue to be more informative?

**Comment by sucrecacao** [comment]
Hi scott, I edited my post to make it more explicit. I hope it help. The goal is not to merge the database to make it nice and modular. The feature would not overlap on other vit feature but I think it would add a real value to it.

**Comment by thehunmonkgroup** [comment]
I can tell you straight out that it's highly unlikely I would accept a pull request for this feature -- it sounds like a logistical nightmare from the code implementation level.

However, a reasonable compromise would be adding:
 * A configuration option to specify 'shortcuts' to various task databases
 * A new action that would allow a user to enter a shortcut name, which would then reload VIT with the task database the shortcut refers to.

Externally, this script gives you an idea of how VIT loads an alternate task database: https://github.com/scottkosty/vit/blob/2.x/scripts/generate-dummy-install.sh

Internally, VIT reads the ```TASKRC``` environment variable (just like TaskWarrior) in order to know which ```.taskrc``` file to parse to access the correct database. You can see this in ```vit/config_parser.py```  under function ```get_taskrc_path```.

**Comment by scottkosty** [comment]
@thehunmonkgroup your ideas on a compromise are interesting, and other users might find it useful. @sucrecacao would you be interested in working on a pull request for those two ideas, even though they don't fully accomplish what you wanted? If you are interested in working on them, we should first work out the interface details before you work on the code.

@sucrecacao Thanks for taking the time to add those extra details. You came up with some use cases that I would not have imagined, and I can see why you would want this behavior. I agree with @thehunmonkgroup regarding it being unlikely to get this in core VIT.

A few comments on your original ideal workflow:

If you can figure this out at the Taskwarrior level, then VIT would never need to know about it because it wouldn't require special treatment. However, I don't think that Taskwarrior would accept something like this either.

You might be able to hack together a sort of interception layer. You already figured out a way for VIT to display things how you want; you just need to figure out how the other direction: how to intercept VIT's modifications and redirect them to the appropriate Taskwarrior database. VIT 2.x communicates with Taskwarrior in various ways. For example (@thehunmonkgroup would know more), VIT 2.x uses https://github.com/robgolding/tasklib to communicate. You could take a look at tasklib to understand how it works. You might be able to take an incoming call (from VIT) and redirect it to the appropriate task database. You just have to figure out how from Tasklib you can tell what should go where, but it should be doable. For example, it shouldn't be too hard to map task UUIDs to task databases. Then, you would get an incoming modification, detect the UUID, and execute the modification on the UUID in the corresponding Taskwarrior database.

I don't actually recommend you do the hackish solution I describe above. It would take time, and would be fragile. But since you took the time to write up all of those details, I did want to give you something to think about.

I don't think I'll be able to help more, but best of luck on your adventure!

**Comment by ahillio** [comment]
This sounds great.  I'm just learning to use taskwarrior and thus instantly feel the **need** for ***vit*** and this feature sounds like a great addition.  I see lots of value in being able to share little project.task files with others and in the other details @sucrecacao describes...

...and the way I read it, it sounds like the details @thehunmonkgroup describes:

>   - A configuration option to specify 'shortcuts' to various task databases
>   - A new action that would allow a user to enter a shortcut name, which would then reload VIT with the task database the shortcut refers to.

would serve completely the goals @sucrecacao described.

the "shortcut to various task databases" sounds to me like it would let you do:
 - from the shell open vit with a particular task file: `vit --taskfile path/to/uni/algorithm` then inside vit you'd be able to perform all your operations on that particular project/taskfile.
 - from inside vit you'd be able to `:use path/to/uni/algorithm` to reload vit from that task database file

So then instead of doing on the commandline:
```
task add read page ... project:uni/algorithm
task add do exercise ... project:uni/algorithm
task add send mail TA project:uni/algorithm
```

You'd be able to do from within vit:
```
a read page ... 
a do exercise ...
a send mail TA
```

This would keep the task files as completely separate, but if someone wants them all aggregated together that seems easily done as an external (not through vit) operation via a shell script (in which case you'd then have a corresponding script, again separate from vit, to take your updates from the all-aggregated-projects.task back to the specific-little-project.task)

@thehunmonkgroup and @scottkosty thanks for your work on this software!  How difficult to achieve would this be?  It sounds to me like the "compromise" @thehunmonkgroup proposed is not actually a compromise but a full solution...?  @sucrecacao do you agree?

**Comment by thehunmonkgroup** [comment]
> How difficult to achieve would this be?

Probably not *too* difficult, but certainly not trivial. And it's not exactly like I have a ton of free time right now, so I would hope somebody else could do the heavy lifting with guidance.

If we go forward with my basic proposal, the first step would be figuring out a sane format for the config option.

**Comment by scottkosty** [comment]
@thehunmonkgroup suppose I switch from task database A to database B and then back to A. Would VIT do a full reload of the data, or would the data be stored from the previous load and VIT would just need to redraw?

**Comment by thehunmonkgroup** [comment]
IIRC, VIT always does a complete reload after every action that interacts with the task database. This may take a little longer, but it's cleaner, and ensures we're working with the latest data after the operation in question.

**Comment by sucrecacao** [comment]
@ahillio
> it sounds like the details @thehunmonkgroup describes [...]
would serve completely the goals @sucrecacao described.

Not really.
My initial goal was to see all the tasks for two or more different taskwarrior database in the same vit instance. Shortcut could be a cool feature, but it will not solve my original problem. 

> the "shortcut to various task databases" sounds to me like it would let you do:
    from the shell open vit with a particular task file: vit --taskfile path/to/uni/algorithm then inside vit 

Can't you already do that with:
`TASKDATA="path/to/uni/algorithm" vit` 

> you'd be able to perform all your operations on that particular project/taskfile.
    from inside vit you'd be able to :use path/to/uni/algorithm to reload vit from that task database file

To jumps from  one taskwarrior db to another, I  we can use simple bash alias like so:
`alias foo="TASKDATA='~/side_project/foo' vit"` 
Pro's: quiting vit and entering the bash alias is shorter in keystroke than typing something like `:use `+ aliasname in the vit command bar. Cons: it a bit more ugly, since you have a transition through your terminal.

**Comment by thehunmonkgroup** [comment]
> Pro's: quiting vit and entering the bash alias is shorter in keystroke than typing something like :use + aliasname in the vit command bar

No, it would be more efficient than that, for the following reasons:
1. The action would be bound to a key, you would not type ```:use``` at all, just hit the keyboard shortcut and enter the alias. Both history and tab completion would be supported for alias names
2. I *believe* you could also map additional keyboard shortcuts to do a direct switch to a particular task database.

**Comment by scottkosty** [comment]
I don't actually know too well how Vim deals with multiple files, but perhaps we could look at how it handles things.

**Comment by thehunmonkgroup** [comment]
Well even in Vim you have to switch between the individual files.

I'm pretty strongly in the camp of:
 * Accepting a PR to add something like the feature I outlined
 * Leaving this more complex edge case to external script processing

**Comment by sucrecacao** [comment]
>  Leaving this more complex edge case to external script processing

Yes, maybe the right implementation is the following:


merge different `.task` folder into a temporary one ( let's say `/tmp/.task_merged` ) . For  every merged task, store its source folder in a dictionary of "uuid" -> "path/to/source/.task"   

Create script with a `sync` function that do the following : for each modification of the merged folder,  apply those modification to the original `.task` folder using the dictionary.  

Open `.task_merged` with vit or favorite front end.  

Then we could trigger the `sync` function with a hook on the front end ( vit ) , or we could use a tool like [`entr` ](https://www.systutorials.com/docs/linux/man/1-entr/) to trigger the `sync` automatically when the merged folder is modified. 

Hope that make senses..  I would love to know your opinion on that

**Comment by thehunmonkgroup** [comment]
Yes, sounds much cleaner than direct VIT integration.

**Comment by sucrecacao** [comment]
I'll do that then. 
Also created a feature request  on the [taskwarrior repo ](https://github.com/GothenburgBitFactory/taskwarrior/issues/2255) but no answer so far.
