### ISSUE TITLE
Keybindings | Add extra replacements or allow command substitution for custom report 

### ISSUE THREAD

**Issue by mohamed-osama-aboelkheir** [vit-project/vit#247]
Currently if i am creating a keybindings for a report it seems the only replacement i can use is {TASK_UUID} , however for some use cases this is not enough.

For example, If i want to create a key binding to show all open tasks in the project of the currently selected task, I need to either:

* Have a replacement for TASK_PROJECT:
`rt=:next project:{TASK_PROJECT}`

* Have the ability to to do command substitution:
`rt=:next project:`task _get {TASK_UUID}.project`<Enter>`

**Comment by thehunmonkgroup** [comment]
The second one sounds pretty dangerous, so that will probably not happen.

I'm open to a PR that exposes other task properties -- it's not something I would spend time on myself at this point.

Finally, I'm wondering if a ```{TASK.[prop]}``` syntax would be better? That would provide more flexibility to task properties, without having to individually expose a bunch of new tokens. It would probably even support UDA fields as a bonus.

**Comment by mohamed-osama-aboelkheir** [comment]
@thehunmonkgroup makes sense :+1:

**Comment by nfraprado** [comment]
I have implemented `TASK_PROJECT` locally as can be seen [here](https://github.com/nfraprado/vit/commit/bc6bea882f2840ec8fb01d1639468d4b5c00701b), and wanted to send it as a PR, but I noticed that when the task didn't have any project, returning an empty string caused an error in the tasklib expression that crashed vit.

I do think the `{TASK.[prop]}` syntax is a better idea and supporting UDAs would be great!

**Comment by thehunmonkgroup** [comment]
@nfraprado, @mohamed-osama-aboelkheir see https://github.com/scottkosty/vit/pull/248

That seems to work fine, and it wasn't too hard to implement.

**Comment by nfraprado** [comment]
Since #248 using `{TASK_PROJECT}` works, so this issue can be closed.

**Comment by thehunmonkgroup** [comment]
So closing....
