### ISSUE TITLE
Newly created context is not autocompletable before app restart

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#254]
Following fix of #253, the autocomplete of newly created context isn't available until the application is restarted.

Autocomplete entries should preferably be updated as soon as new contexts are spotted/contexts are reloaded.

**Comment by thehunmonkgroup** [comment]
VIT does not proactively monitor for changes in any configuration files.

It's doubtful that this feature will be added, especially when a simple ```Ctrl+l``` will reload all configuration.

#253 reloads the context configuration in response to a request to change context, which is why it can know about the newly created context. In this special case of creating a new context and immediately trying to switch to it (without reloading VIT via ```Ctrl+l```), there is no practical way to populate the autocomplete.
