### ISSUE TITLE
Blank screen for a second after task modification

### ISSUE THREAD

**Issue by arozans** [vit-project/vit#273]
**Describe the bug**
When editing a task with 'm' command and with option 'wait' set to False there is a brief moment when screen is blank (looks like "wait" screen is displayed for short period of time before vit decides that it should be skipped accordingly to disabled option).

**To Reproduce**
set wait = False in .ini file and then execute any modification via 'm' (or 't') command (note: editing via 'p' for example doesn't produce such behavior)

**Expected behavior**
For me it would be preferable if the behavior was the same as when editing via 'p' - only edited row flashes few times.

P.S. Thanks for this tool. It's a fantastic addition to the taskwarrior, should be advertised on its main page, no more tedious ids checking.

**Comment by thehunmonkgroup** [comment]
VIT uses `task modify` for that command, and not the `tasklib` library.

By design, any VIT command that leverages `task` directly shows the output of the task command. `wait = False` simply disables having to hit enter after the output from `task` has rendered.

I don't believe refactoring this would be simple, and doesn't seem worth the effort just to solve a minor display issue.

I would consider a PR from somebody that addresses a fix cleanly, and doesn't complicate the code base.
