### ISSUE TITLE
Quit command mode when pressing backspace in an empty command bar

### ISSUE THREAD

**Issue by champignoom** [vit-project/vit#274]
**Is your feature request related to a problem? Please describe.**

Press `:`, press `<backspace>`. The colon should then disappear and vit return to normal mode.
This is how (neo)vim behaves.

**Describe the solution you'd like**

Add a conditional statement.

**Additional context**

None.

**Comment by scottkosty** [comment]
In mutt the default is to not have this special behavior. in NeoMutt the default is to have it, and they provide an option:

```
abort_backspace
       Type: boolean
       Default: yes

       If set, hitting backspace against an empty prompt aborts the prompt.
```

I don't have a preference on the behavior. I'm just adding the above as more info on what other TUI apps do.

**Comment by nfraprado** [comment]
Personally I'd prefer if that was implemented as an option, since I wouldn't want that behavior.

With that behavior the user can accidentally leave EX mode when erasing to fix a command if they type one extra backspace.
Leaving EX mode with the Escape key instead seems much more robust to me, as it won't be pressed by mistake and can be pressed at any point in the command.

**Comment by thehunmonkgroup** [comment]
If somebody wants to make a PR for it, I'd consider adding it as a configurable option, as long as it doesn't make the code messy.
