### ISSUE TITLE
Feature Request: Add/Attach Blocker/Blocked

### ISSUE THREAD

**Issue by darkpixel** [vit-project/vit#298]
I would love to see a feature added so you can highlight an existing task and then add a related blocker or block the existing task with a new ticket.

For example, if I created a task "Get milk from the store", I would like to highlight it and add a brand new blocker "Get gas for car".

Currently, you would have to add "Get milk from the store", then open up the details to get the ID or UUID, then add "Get gas for car", then edit it, paste in the ID/UUID, and save it.

Additionally, the ability to select an existing item, hit "Attach blocked" or "Attach blocker" and then navigate to another existing task and hitting enter to associate them would be amazing.

It would help when creating a complex series of steps.
When I manage the opening of a new office, there are around 150 todo items that are related to each other in various ways.

i.e. "Install Server Equipment" is interdependent with things like "Spec equipment", "Get quotes", "Get approval", "Order Equipment", "Configure equipment", "Inventory equipment", "Test equipment", etc...  "Configure equipment" has a handful of related items too like "Ensure switch port x is on VLAN y", "Configure UPS with settings abc", etc...

**Comment by scottkosty** [comment]
Nice idea, @darkpixel. @thehunmonkgroup I wonder if the plugin architecture you have in mind down the road could handle this type of feature.

**Comment by nfraprado** [comment]
Adding a new blocked task is pretty easy with variable substitution. You could have a mapping that adds a new task with the selected task's UUID as its dependency with:
```
a = {ACTION_TASK_ADD}
aB = adep:{TASK_UUID}<Space>
```

I'm not sure how to do the other way around though: adding a task that blocks the currently selected one.

**Comment by thehunmonkgroup** [comment]
OK, couple of things here:

First, that above keybinding config will not work, generating this error:

```
vit.key_cache.KeyCacheError: Invalid key binding 'aB', 'a' already used in another key binding
```

You can't make a keybinding that starts with another keybinding, VIT prevents that because it cannot determine which keybinding you'd want in that case.

So you need to pick a custom keybinding that doesn't conflict with an existing one.

Second, I'm not aware of any mechanism like `depends:` that you can give TaskWarrior when adding a task that would make it block another task. *However*, you can script this if you can get access to the currently selected task UUID in the script.

So, I've tentatively added that feature to the development branch of VIT. When executing external commands, VIT now sets the `VIT_TASK_UUID` environment variable to the currently selected task. If it cannot determine the currently selected task, that environment variable will be empty.

With that in place, you can have keybindings like this:

```dosini
  [keybinding]
  
  ZD = adepends:{TASK_UUID}<Space>
  ZB = :!wr add-blocking.sh<Space>
```

...and the add-blocking.sh script (executable and in your PATH) like this:

```bash
#!/usr/bin/env bash

echo "Selected task uuid is: ${VIT_TASK_UUID}"
task add "$@"
LAST_UUID="$(task +LATEST uuids)"
echo "Added task uuid is: ${LAST_UUID}"
task modify ${VIT_TASK_UUID} depends:${LAST_UUID}
```

Try that out on the development branch of VIT and see if it works OK. I can't guarantee that feature will make it into a release yet, but it does seem handy to have access to the currently selected task UUID in scripts, so it *probably* will be added in some form.

**Comment by nfraprado** [comment]
Oops. I actually use `aa` (and unmap `a`) in my bindings. I omitted that here to be more concise but ended up causing more confusion. Sorry about that!

**Comment by thehunmonkgroup** [comment]
Pretty sure my solution above fixes this issue.
