### ISSUE TITLE
Failure to add a task containing special characters

### ISSUE THREAD

**Issue by hugoh** [vit-project/vit#301]
**Describe the bug**

Certain characters such as `'` make adding a task fail silently. Some escaping seems needed somewhere.

**To Reproduce**

- Press `a` to add a task
- Use `a'b` as the description
- Press enter

The prompt goes away and nothing happens.

**Expected behavior**

A task named `a'b` is created.

**Comment by thehunmonkgroup** [comment]
I believe any escaping strategy would make the add command less flexible. What you're seeing is basically the same behavior you'd see at the command line, except you don't get any visual feedback, and you can't continue the  command as you would be able to with the command line, it is simply thrown away.

Since I don't want to reduce the flexibility of the add command, I will not introduce escaping.

You'll need to provide the escaping yourself, like so:

`a\'b`

The lack of interface feedback is a separate issue, and one I don't immediately have a good solution for. You're welcome to file another issue for that, but I'd probably need somebody to step up to help.
